ObligatorioP3/ObligatorioP3/Controllers/FinanciadorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ObligatorioP3.Models;

namespace ObligatorioP3.Controllers
{
    public class FinanciadorsController : Controller
    {
        private ObliEmprendimientosContext db = new ObliEmprendimientosContext();

        // GET: Financiadors/Create
        public ActionResult Create()
        {
            ViewBag.Mensaje = "";
            return View();
        }

        // POST: Financiadors/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,Password,Rol,Organizacion,MontoMax")] Financiador financiador)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Mensaje = "";

                var usuarioExistente = db.Usuarios.Where(u => u.Email == financiador.Email).SingleOrDefault();

                if(usuarioExistente != null)
                {
                    ViewBag.Mensaje = "El mail utilizado para registrarse ya fue utilizado.";
                }
                else
                {
                    db.Usuarios.Add(financiador);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Emprendimientoes");
                }
            }

            return View(financiador);
        }

        // Metodo autogenerado
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ObligatorioP3/ObligatorioP3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Emprende Net!</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @{ ObligatorioP3.Models.Usuario usuario = Session["Usuario"] as ObligatorioP3.Models.Usuario; }
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Emprende Net!", "Index", "Emprendimientoes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Emprendimientoes")</li>
                    @{
                        ObligatorioP3.Models.Financiador financiador = usuario as ObligatorioP3.Models.Financiador;

                        if (financiador != null)
                        {
                            TempData["financiadorId"] = financiador.Id;
                            <li>@Html.ActionLink("Mis Emprendimientos", "EmprendimientosFinanciados", "Emprendimientoes")</li>
                            <li>@Html.ActionLink("Listado Mejores", "IndexRankMejores", "Emprendimientoes")</li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @{
                        if (usuario != null)
                        {
                            <li><p class="navbar-text">@usuario.Email</p></li>
                            <li>@Html.ActionLink("Log out", "Logout", "Usuario")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Registrarse", "Create", "Financiadors")</li>
                            <li>@Html.ActionLink("Log in", "Login", "Usuario")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year | Emprende Net!</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>