ObligatorioP3/ObligatorioP3/Controllers/EmprendimientoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ObligatorioP3.Models;
using System.IO;

namespace ObligatorioP3.Controllers
{
    public class EmprendimientoesController : Controller
    {
        private ObliEmprendimientosContext db = new ObliEmprendimientosContext();

        // GET: Emprendimientos finaciados por autenticado
        public ActionResult EmprendimientosFinanciados()
        {
            ActionResult ret = View();
            ViewBag.MensajeNoTiene = "";
            int financiadorId = (int)TempData["financiadorId"];
            Financiador financiador = db.Usuarios.Find(financiadorId) as Financiador;
            var emprendimientosMios = from e in db.Emprendimientos.Include("Financiador") select e;
            emprendimientosMios = emprendimientosMios.Where(e => e.Financiador.Id == financiadorId);
            if (emprendimientosMios.Count() == 0)
            {
                ViewBag.MensajeNoTiene = "No tienes ningun emprendimiento financiado";
            }
            else
            {
                ret = View(emprendimientosMios.ToList());
            }

            return ret;
        }

        // GET: Emprendimientoes
        public ActionResult Index(string sortOrder, string costoMin, string costoMax, string tiempoMax, bool? financiable)
        {
            var emprendimientos = from e in db.Emprendimientos.Include("Financiador") select e;
            ViewBag.MensajeInicializar = "";

            if (emprendimientos.Count() == 0)
            {
                ViewBag.MensajeInicializar = "No hay emprendimientos en el sistema, es necesario ";
            }
            else
            {
                if (!String.IsNullOrEmpty(costoMin))
                {
                    decimal costoMinD;
                    bool costoMinOk = decimal.TryParse(costoMin, out costoMinD);
                    if (costoMinOk)
                    {
                        emprendimientos = emprendimientos.Where(e => e.Costo >= costoMinD);
                    }
                }

                if (!String.IsNullOrEmpty(costoMax))
                {
                    decimal costoMaxD;
                    bool costoMaxOk = decimal.TryParse(costoMax, out costoMaxD);
                    if (costoMaxOk)
                    {
                        emprendimientos = emprendimientos.Where(e => e.Costo <= costoMaxD);
                    }
                }

                if (!String.IsNullOrEmpty(tiempoMax))
                {
                    decimal tiempoMaxD;
                    bool tiempoMaxOk = decimal.TryParse(tiempoMax, out tiempoMaxD);
                    if (tiempoMaxOk)
                    {
                        emprendimientos = emprendimientos.Where(e => e.Tiempo <= tiempoMaxD);
                    }
                }

                if (Session["Usuario"] != null)
                {
                    Financiador f = Session["Usuario"] as Financiador;
                    if (f != null)
                    {
                        if (financiable != null && financiable == true)
                        {
                            emprendimientos = emprendimientos.Where(e => e.Costo <= f.MontoMax && e.Financiador == null);
                        }
                    }
                }

                ViewBag.CostoSortParm = sortOrder == "costo_asc" ? "costo_desc" : "costo_asc";

                switch (ViewBag.CostoSortParm as string)
                {
                    case "costo_asc":
                        emprendimientos = emprendimientos.OrderBy(e => e.Costo);
                        break;
                    case "costo_desc":
                        emprendimientos = emprendimientos.OrderByDescending(e => e.Costo);
                        break;
                }

                return View(emprendimientos.ToList());
            }

            return View(emprendimientos.ToList());
        }
        // GET:Mejores  Emprendimientoes
        public ActionResult IndexRankMejores()
        {
            ActionResult ret = View();
            List<Emprendimiento> emprendimientosOrdenados = db.Emprendimientos.OrderByDescending(e => e.PuntajeTotal).ToList();
            int cantEmprend = emprendimientosOrdenados.Count();
            if (cantEmprend == 0)
            {
                ViewBag.MensajeInicializar = "No hay emprendimientos en el sistema, es necesario ";
            }
            else
            {
                decimal res = (decimal)cantEmprend / 10;
                int valor = (int)Math.Ceiling(res);
                ret = View(emprendimientosOrdenados.Take(valor).ToList());
            }
            return ret;
        }

        // GET: Emprendimientoes/Details/5
        [HttpGet]

        public ActionResult Details(int? id, string mensaje)
        {
            ViewBag.FinanciarSuccess = "";
            ViewBag.FinanciarError = "";

            if (!String.IsNullOrEmpty(mensaje))
            {
                switch (mensaje)
                {
                    case "success":
                        ViewBag.FinanciarSuccess = "Felicitaciones! Usted es el Financiador de este proyecto";
                        break;
                    case "error_ya_financiado":
                        ViewBag.FinanciarError = "Este Emprendimiento ya cuenta con un Financiador";
                        break;
                    case "error_costo_elevado":
                        ViewBag.FinanciarError = "Usted no puede permitirse el costo de este emprendimiento";
                        break;
                }
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Emprendimiento emprendimiento = db.Emprendimientos.Include("Financiador")
                                            .Where(e => e.Id == id).SingleOrDefault() as Emprendimiento;

            if (emprendimiento == null)
            {
                return HttpNotFound();
            }
            return View(emprendimiento);
        }

        public ActionResult Inicializar()
        {
            string path = Server.MapPath("~/ArchivoTexto/WCFarchivo.txt");
            StreamReader sReader = new StreamReader(path);
            string linea = "";

            while ((linea = sReader.ReadLine()) != null)
            {
                string[] lineaSplit = linea.Split('#');

                decimal costo = 0;
                bool okCosto = decimal.TryParse(lineaSplit[2], out costo);
                int duracion = 0;
                bool okDuracion = int.TryParse(lineaSplit[3], out duracion);
                int puntajeTotal = 0;
                bool okPuntaje = int.TryParse(lineaSplit[4], out puntajeTotal);

                if (okCosto && okDuracion && okPuntaje)
                {
                    Emprendimiento emprendimiento = new Emprendimiento
                    {
                        Titulo = lineaSplit[1],
                        Costo = costo,
                        Tiempo = duracion,
                        PuntajeTotal = puntajeTotal,
                        Descripcion = lineaSplit[5]
                    };
                    db.Emprendimientos.Add(emprendimiento);
                }
            }
            sReader.Close();
            db.SaveChanges();

            return (RedirectToAction("Index"));
        }

        public ActionResult Financiar()
        {
            ViewBag.FinanciarSuccess = "";
            ViewBag.FinanciarError = "";

            int financiadorId = (int)TempData["financiadorId"];
            int emprendimientoId = (int)TempData["emprendimientoId"];

            Emprendimiento emprendimiento = db.Emprendimientos.Include("Financiador")
                                            .Where(e => e.Id == emprendimientoId).SingleOrDefault() as Emprendimiento;

            Financiador financiador = db.Usuarios.Find(financiadorId) as Financiador;

            if (emprendimiento == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                if (emprendimiento.Financiador == null) // Lo traigo fresco de la BD para evitar problemas de concurrencia
                {
                    if (emprendimiento.Costo <= financiador.MontoMax)
                    {
                        emprendimiento.Financiador = financiador;
                        db.SaveChanges();
                        return (RedirectToAction("Details", new { id = emprendimientoId, mensaje = "success" }));
                    }
                    else
                    {
                        return (RedirectToAction("Details", new { id = emprendimientoId, mensaje = "error_costo_elevado" }));
                    }
                }
                else
                {
                    return (RedirectToAction("Details", new { id = emprendimientoId, mensaje = "error_ya_financiado" }));
                }
            }
        }

        // Este método se generó solo, así que por las dudas lo dejo
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ObligatorioP3/ObligatorioP3/Views/Emprendimientoes/Details.cshtml
@model ObligatorioP3.Models.Emprendimiento

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Emprendimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Costo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Costo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tiempo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tiempo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PuntajeTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PuntajeTotal)
        </dd>

    </dl>
</div>
@if (ViewBag.FinanciarSuccess != "")
{
    <p class="alert alert-success text-center">
        @ViewBag.FinanciarSuccess
    </p>
}
else if (ViewBag.FinanciarError != "")
{
    <p class="alert alert-danger text-center">
        @ViewBag.FinanciarError
    </p>
}
<p>
    @Html.ActionLink("Back to List", "Index")
    @if (Session["Usuario"] != null)
    {
        ObligatorioP3.Models.Financiador financiador = Session["Usuario"] as ObligatorioP3.Models.Financiador;

        if (financiador != null && Model.Financiador == null)
        {
            <span> | </span>
            TempData["emprendimientoId"] = Model.Id;
            TempData["financiadorId"] = financiador.Id;
            @Html.ActionLink("Financiar", "Financiar", "Emprendimientoes")
        }
    }
    </p>

ObligatorioP3/ObligatorioP3/Views/Emprendimientoes/EmprendimientosFinanciados.cshtml
@model IEnumerable<ObligatorioP3.Models.Emprendimiento>

@{
    ViewBag.Title = "EmprendimientosFinanciados";
}

<h2>Mis Emprendimientos</h2>

@if (ViewBag.MensajeNoTiene != "")
{
    <p class="alert">
        @ViewBag.MensajeNoTiene
    </p>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Costo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tiempo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PuntajeTotal)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Costo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tiempo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PuntajeTotal)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                      @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                      @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
                </td>
            </tr>
        }

    </table>
}

ObligatorioP3/ObligatorioP3/Views/Emprendimientoes/Index.cshtml
@model IEnumerable<ObligatorioP3.Models.Emprendimiento>

@{
    ViewBag.Title = "Emprendimientos";
}

<h2>Emprendimientos</h2>

@if (ViewBag.MensajeInicializar != "")
{
    <p class="alert alert-danger">
        @ViewBag.MensajeInicializar<span>@Html.ActionLink("inicializar la aplicacion", "Inicializar")</span>
    </p>
}

    <div class="pull-right" style="margin-top: 10px">
        @using (Html.BeginForm("Index", "Emprendimientoes",
        FormMethod.Post, new { @class = "form-inline" }))
        {
        <div class="form-group">
            <label for="costoMin">Costo mínimo:</label>
            @Html.TextBox("costoMin")
        </div>
        <div class="form-group">
            <label for="costoMax">Costo máximo:</label>
            @Html.TextBox("costoMax")
        </div>
        <div class="form-group">
            <label for="tiempoMax">Duración máxima:</label>
            @Html.TextBox("tiempoMax")
        </div>

            if (Session["Usuario"] != null)
            {
                ObligatorioP3.Models.Financiador financiador = Session["Usuario"] as ObligatorioP3.Models.Financiador;

                if (financiador != null)
                {
                    <div class="checkbox">
                        @Html.CheckBox("financiable")
                        <label for="financiable">Lo puedo financiar</label>
                    </div>
                }
            }

        <input type="submit" value="Filtrar" class="btn btn-default" />
        }
    </div>

<div class="clearfix"></div>
<table class="table" style="margin-top: 10px">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th title="Ordenar por Costo">
            @Html.ActionLink("Costo", "Index", new { sortOrder = ViewBag.CostoSortParm })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tiempo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PuntajeTotal)
        </th>
        <th>
            Estado
        </th>
        <th></th>
    </tr>
@{ int i = 0; }
@foreach (var item in Model) {
    i++;
    <tr>
        <td>
            @i
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Costo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tiempo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PuntajeTotal)
        </td>
        <td>
            @if (item.Financiador == null)
            {
                <p class="text-success">Sin financiamiento</p>
            }
            else
            {
                <p class="text-danger">Financiado</p>
            }
        </td>
        <td>
            @Html.ActionLink("Ver", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>

ObligatorioP3/ObligatorioP3/Views/Emprendimientoes/IndexRankMejores.cshtml
@model IEnumerable<ObligatorioP3.Models.Emprendimiento>

@{
    ViewBag.Title = "Ranking de los mejores Emprendimientos (10%)";
}

<h2>Ranking de los mejores Emprendimientos (10%)</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Costo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tiempo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PuntajeTotal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Costo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tiempo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PuntajeTotal)
        </td>
        <td>           
            @Html.ActionLink("Details", "Details", new { id=item.Id })             
        </td>
    </tr>
}

</table>

ObligatorioP3/ObligatorioP3/Views/Emprendimientoes/misEmprendimientosFinanciados.cshtml
@model IEnumerable<ObligatorioP3.Models.Emprendimiento>

@{
    ViewBag.Title = "Mis Emprendimientos";
}

<h2>Mis Emprendimientos</h2>

    @if (ViewBag.MensajeInicializar != "")
    {
    <p class="alert">
        @ViewBag.MensajeNoTiene
    </p>
    }
    else
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Titulo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Costo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tiempo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PuntajeTotal)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Titulo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Costo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tiempo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PuntajeTotal)
                    </td>
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
                    </td>
                </tr>
            }

        </table>
    }